### ISSUE TITLE
Unable to build in Ubuntu 20.04

### ISSUE THREAD

**Issue by micmelesse** [ultralight-ux/ultralight-quick-start#4]
Hi I am trying to build the examples in Ubuntu 20.04 but it fails with 

```
[ 72%] Built target UltralightSDK
[ 81%] Linking CXX executable MyApp
/usr/bin/ld: warning: libpng12.so.0, needed by /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libffi.so.6, needed by /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_interlace_handling@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_create_write_struct@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_get_color_type@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_write_end@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_compression_level@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_add_alpha@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_get_IHDR@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_float'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_palette_to_rgb@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_process_data@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_sint64'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_write_image@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_pointer'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_write_info@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_read_update_info@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_sint32'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_write_fn@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_uint64'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_filter@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_gray_1_2_4_to_8@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_destroy_info_struct@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_void'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_create_info_struct@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_uint32'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_get_io_ptr@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_call'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_get_bit_depth@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_destroy_write_struct@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_type_double'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgobject-2.0.so.0: undefined reference to `ffi_prep_cif'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_destroy_read_struct@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_create_read_struct@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_error@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_swap@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_gray_to_rgb@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_progressive_read_fn@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_progressive_combine_row@PNG12_0'
/usr/bin/ld: /home/micmelesse/code/ultralight-quick-start/build/SDK/bin/libgstreamer-full-1.0.so: undefined reference to `png_set_IHDR@PNG12_0'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MyApp.dir/build.make:113: MyApp] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/MyApp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by egihasdi** [comment]
I had same issue, my workaround:
1. install libpng12 https://askubuntu.com/questions/1194386/how-to-correctly-install-libpng12-0-on-the-ubuntu-19-10
2. link libffi 7 to 6 https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6

**Comment by micmelesse** [comment]
@egiw Thank you. This resolved my issue.
